# Dependencies
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# File rules
exclude:
  # default excludes
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # custom excludes
  - Makefile
  - Dangerfile
  - LICENSE
  - README.md
  - package.json
  - yarn.lock
  - .yarnrc
  - scripts/
  - .github/

include:
  - _redirects
  - .htaccess
  # dependencies
  - yarn_deps/bootstrap/dist/css/bootstrap.min.css
  - yarn_deps/bootstrap/dist/css/bootstrap.min.css.map
  - yarn_deps/bootstrap/dist/js/bootstrap.bundle.min.js
  - yarn_deps/bootstrap/dist/js/bootstrap.bundle.min.js.map
  - yarn_deps/jquery/dist/jquery.slim.min.js

# Site
permalink: /:year/:month/:day/:title/
img_url: /img
excerpt_separator: <!--excerpt-->
sass:
  style: compressed

# Metadata
title: 'TWC Newsletter'
description: 'News and inspiration for worker power in the tech industry'
url: https://news.techworkerscoalition.org
logo: /img/newsletter-team.png
timezone: America/Los_Angeles

# Author
author:
  name: 'Tech Workers Coalition'
  twitter: twcnewsletter
  avatar: /img/newsletter-team.png

links:
  github: https://github.com/techworkersco/techworkersco.github.io

feeds:
  rss: '/feed.xml'
  json: '/feed.json'
  limit: 30
